// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logos.sql

package database

import (
	"context"
	"database/sql"
)

const getLogoBySourceID = `-- name: GetLogoBySourceID :one
SELECT id, source_id, object_key, url, mime_type, size_bytes, created_at, updated_at
FROM logos
WHERE source_id = $1
`

func (q *Queries) GetLogoBySourceID(ctx context.Context, sourceID string) (Logo, error) {
	row := q.db.QueryRowContext(ctx, getLogoBySourceID, sourceID)
	var i Logo
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ObjectKey,
		&i.Url,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLogo = `-- name: UpsertLogo :one
INSERT INTO logos (
  source_id,
  object_key,
  url,
  mime_type,
  size_bytes
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (source_id) DO UPDATE SET
  object_key = EXCLUDED.object_key,
  url = EXCLUDED.url,
  mime_type = EXCLUDED.mime_type,
  size_bytes = EXCLUDED.size_bytes,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, source_id, object_key, url, mime_type, size_bytes, created_at, updated_at
`

type UpsertLogoParams struct {
	SourceID  string
	ObjectKey string
	Url       string
	MimeType  sql.NullString
	SizeBytes sql.NullInt64
}

func (q *Queries) UpsertLogo(ctx context.Context, arg UpsertLogoParams) (Logo, error) {
	row := q.db.QueryRowContext(ctx, upsertLogo,
		arg.SourceID,
		arg.ObjectKey,
		arg.Url,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Logo
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ObjectKey,
		&i.Url,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
