// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Link        string
	Guid        string
	PubDate     time.Time
	SourceID    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Source struct {
	ID        string
	Name      string
	Url       string
	Category  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
