// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts  (
  title,
  description,
  link,
  guid,
  pub_date,
  source_id
) VALUES ($1,$2,$3,$4,$5, $6)
ON CONFLICT (guid) 
DO UPDATE SET guid = EXCLUDED.guid
RETURNING id, title, description, link, guid, pub_date, source_id, status, created_at, updated_at
`

type CreatePostParams struct {
	Title       string
	Description sql.NullString
	Link        string
	Guid        string
	PubDate     time.Time
	SourceID    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Guid,
		arg.PubDate,
		arg.SourceID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Guid,
		&i.PubDate,
		&i.SourceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deduplicatePosts = `-- name: DeduplicatePosts :one
INSERT INTO posts (
  title,
  description,
  link,
  guid,
  pub_date,
  source_id
) 
  VALUES ($1,$2,$3,$4,$5,$6) 
  ON CONFLICT (guid) DO NOTHING
  RETURNING guid
`

type DeduplicatePostsParams struct {
	Title       string
	Description sql.NullString
	Link        string
	Guid        string
	PubDate     time.Time
	SourceID    string
}

func (q *Queries) DeduplicatePosts(ctx context.Context, arg DeduplicatePostsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deduplicatePosts,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Guid,
		arg.PubDate,
		arg.SourceID,
	)
	var guid string
	err := row.Scan(&guid)
	return guid, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
  WHERE id == $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, description, link, guid, pub_date, source_id, status, created_at, updated_at
  FROM posts
  WHERE id == $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Guid,
		&i.PubDate,
		&i.SourceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, description, link, guid, pub_date, source_id, status, created_at, updated_at FROM posts
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Link,
			&i.Guid,
			&i.PubDate,
			&i.SourceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsForSource = `-- name: ListPostsForSource :many
SELECT id, title, description, link, guid, pub_date, source_id, status, created_at, updated_at
  FROM posts
  WHERE LOWER(source_id) = ANY($1::TEXT[])
`

func (q *Queries) ListPostsForSource(ctx context.Context, dollar_1 []string) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsForSource, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Link,
			&i.Guid,
			&i.PubDate,
			&i.SourceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
  SET title = $1,
    description = $2,
    link = $3,
    guid = $4,
    pub_date = $5,
    source_id = $6,
    status = 'done'
  WHERE guid = $4
  RETURNING id, title, description, link, guid, pub_date, source_id, status, created_at, updated_at
`

type UpdatePostParams struct {
	Title       string
	Description sql.NullString
	Link        string
	Guid        string
	PubDate     time.Time
	SourceID    string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Guid,
		arg.PubDate,
		arg.SourceID,
	)
	return err
}
