services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: colibri_db
    secrets:
      - db-password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      update_config:
        order: start-first

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER_FILE=/run/secrets/rabbitmq-user
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/rabbitmq-password
      - RABBITMQ_DEFAULT_VHOST=colibri-vhost
    secrets:
      - rabbitmq-user
      - rabbitmq-password
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      update_config:
        order: start-first

  migrate:
    build:
      context: .
      dockerfile: cmd/migrate/Dockerfile
    image: maximebourret/colibri-migrate:latest
    environment:
      DB_DRIVER: "postgres"
      DB_STRING_FILE: /run/secrets/db-string
    secrets:
      - db-string
    depends_on:
      - postgres

  consumer:
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    image: maximebourret/colibri-consumer:latest
    environment:
      AMQP_URL_FILE: /run/secrets/rabbitmq-url
      DB_DRIVER: "postgres"
      DB_STRING_FILE: /run/secrets/db-string
    secrets:
      - rabbitmq-url
      - db-string
      - google-api-key
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure
    deploy:
      update_config:
        order: start-first
      replicas: 4

  api:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    image: maximebourret/colibri-api:latest
    environment:
      DB_DRIVER: "postgres"
      DB_STRING: db-string
    secrets:
      - db-string
    depends_on:
      - postgres
    restart: on-failure
    deploy:
      update_config:
        order: start-first

  fetcher:
    build:
      context: .
      dockerfile: cmd/fetcher/Dockerfile
    image: maximebourret/colibri-fetcher:latest
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - consumer
    deploy:
      restart_policy:
        condition: any
        delay: 4h

volumes:
  pgdata:

secrets:
  db-password:
    external: true
  db-string:
    external: true
  google-api-key:
    external: true
  rabbitmq-user:
    external: true
  rabbitmq-password:
    external: true
  rabbitmq-url:
    external: true
