services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colibri_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: cmd/migrate/Dockerfile
    image: maximebourret/colibri-migrate:latest
    environment:
      DB_DRIVER: "postgres"
      DB_STRING: "postgresql://postgres:postgres@postgres:5432/colibri_db?sslmode=disable"
    depends_on:
      - postgres

  consumer:
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    image: maximebourret/colibri-consumer:latest
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      DB_DRIVER: "postgres"
      DB_STRING: "postgresql://postgres:postgres@postgres:5432/colibri_db?sslmode=disable"
    secrets:
      - google-api-key
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure
    deploy:
      replicas: 4

  api:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    image: maximebourret/colibri-api:latest
    environment:
      DB_DRIVER: "postgres"
      DB_STRING: "postgresql://postgres:postgres@postgres:5432/colibri_db?sslmode=disable"
    depends_on:
      - postgres
    restart: on-failure

  fetcher:
    build:
      context: .
      dockerfile: cmd/fetcher/Dockerfile
    image: maximebourret/colibri-fetcher:latest
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - consumer
    deploy:
      restart_policy:
        condition: any
        delay: 4h

volumes:
  pgdata:

secrets:
  google-api-key:
    file: ./google_api_key.txt
