services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colibri_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./description_agent_prompt.md:/app/config/description_agent_prompt.md
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      DB_DRIVER: "postgres"
      DB_STRING: "postgresql://postgres:postgres@postgres:5432/colibri_db?sslmode=disable"
    secrets:
      - google-api-key
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure
    deploy:
      replicas: 4

  api:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DB_DRIVER: "postgres"
      DB_STRING: "postgresql://postgres:postgres@postgres:5432/colibri_db?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:

secrets:
  google-api-key:
    file: ./google_api_key.txt
