-- +goose Up
CREATE TABLE sources (
  id VARCHAR PRIMARY KEY,
  name VARCHAR NOT NULL,
  url TEXT NOT NULL,
  category VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS sources;
